kgtube/urls.py
from django.contrib import admin
from django.urls import path
from core.views import *
from playlist.views import *
# from playlist import views
from video.views import *
from django.conf import settings
from django.conf.urls.static import static
from shorts.views import *



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', videos, name="home"),
    path('about/', about_view),
    path('playlists/', playlists),
    # path('playlists/', views.playlists),
    path('playlist/<int:id>/', playlist_info, name='playlist-info'),
    path('playlist/add/', playlist_add, name='playlist-add'),
    path('playlist-df/add/', playlist_df_add, name='playlist-df-add'),
    path('videos/', videos),
    path('video/<int:id>/', video),
    path('video-update/<int:id>/', video_update, name='video-update'),
    path('video-update-cbv/<int:pk>/', VideoUpdate.as_view(), name='video-update-cbv'),
    path('video-delete/<int:id>/', video_delete, name='video-delete'),
    path('video-add/', video_add, name='video-add'),
    path('search/', search, name='search'), # from core.views import search
    path('profile-create/', profile_create, name='profile-create'),
    path('profile/<int:id>/', profile_detail, name='profile-detail'),
    path('profile-update/<int:id>/', profile_update, name='profile-update'),
    path('profile-delete/<int:id>/', profile_delete, name='profile-delete'),
    path('profile-update-cbv/<int:pk>/', ProfileUpdate.as_view(), name='profile-update-cbv'),
    path('subscriber-add/<int:id>/', subscriber_add, name='subscriber-add'),
    path('subscriber-remove/<int:id>/', subscriber_remove, name='subscriber-remove'),
    path('registration/', registration, name="registration"),
    path('sign-in/', sign_in, name="sign-in"),
    path('sign-out/', sign_out, name="sign-out"),
    path('shorts/', short_list, name='short_list'),
    path('create/', short_create, name='short_create'),
    path('<int:pk>/', short_detail, name='short_detail'),
    path('<int:pk>/update/', short_update, name='short_update'),
    path('<int:pk>/delete/', short_delete, name='short_delete'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video/models.py
from django.db import models
from django.contrib.auth.models import User
from playlist.models import UserPlayList

# Create your models here.
class Video(models.Model):
    file_path = models.FileField(upload_to="video/") # путь к видео файлу
    name = models.CharField(max_length=60) # varchar
    likes = models.IntegerField(default=0) # int
    dislikes = models.ManyToManyField(User, related_name='disliked_videos')
    description = models.TextField(null=True) # text # blank = False
    is_published = models.BooleanField(default=True) # boolean
    playlist = models.ForeignKey(
        to=UserPlayList,
        on_delete=models.SET_NULL,
        null=True, blank=True
    )
    author = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        null=True,
        blank=False
    )

    def __str__(self):
        return self.name


class Comment(models.Model):
    txt = models.TextField(verbose_name="Текст комментария")
    video = models.ForeignKey(
        to=Video,
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE
    )
    created_by = models.DateTimeField(auto_now_add=True)
    updated_by = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.txt[:10]


class VideoView(models.Model):
    video = models.ForeignKey(
        to=Video,
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE
    )
    created_by = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Просмотр"
        verbose_name_plural = "Просмотры"
        unique_together = [["video", "user"]]

core/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            "channel_name",
            "photo"
        ]


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username", "password",
            "first_name", "last_name"
        ]

class UserAuthForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        fields = ["username", "password"]
   

playlist/forms.py
from django import forms
from .models import UserPlayList


class PlayListForm(forms.ModelForm):
    class Meta:
        model = UserPlayList
        fields = ['name', 'description', 'videos_qty']

video/forms.py
from django import forms
from .models import *


class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['name', 'description']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['txt']

core/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.views import View
from django.db.models import Q
from video.models import Video
from .models import Profile
from .forms import *


def registration(request):
    if request.user.is_authenticated:
        return redirect("home")

    context = {}
    if request.method == "POST":
        registration_form = UserCreateForm(request.POST)
        if registration_form.is_valid():
            new_user = registration_form.save(commit=False)
            new_user.set_password(request.POST["password"])
            new_user.save()
            Profile.objects.create(
                channel_name=new_user.username,
                user=new_user
            )
            messages.success(request, "Вы успешно прошли регистрацию")

    context["registration_form"] = UserCreateForm()
    return render(request, "user/registration.html", context)


def sign_in(request):
    if request.user.is_authenticated:
        return redirect("home")
    

    if request.method == "POST":
        auth_form = UserAuthForm(request.POST)
        if auth_form.is_valid():
            # индентификация
            user_object = authenticate(
                username=request.POST["username"],
                password=request.POST.get("password")
            )
            # авторизация
            if user_object:
                login(request, user_object)
                messages.success(request, "Успешно авторизовано!")
            else:
                messages.error(request, "Неверный логин или пароль")
        else:
            # print(auth_form.errors)
            messages.error(request, auth_form.errors)  
            
    return render(
        request,
        "user/sign_in.html",
        {"auth_form": UserAuthForm()}
    )

def sign_out(request):
    logout(request)
    return redirect("home")

# Create your views here.
def homepage(request):
    # return HttpResponse("hello world")
    return render(request, "home.html")

def about_view(request):
    return render(request, 'about.html')

def search(request):
    key_word = request.GET["key_word"]
    # SELECT * FROM Video WHERE name LIKE '%key_word%'
    # videos_query = Video.objects.filter(name__contains=key_word)
    # videos_query = Video.objects.filter(description__contains=key_word)
    videos_query = Video.objects.filter(
        Q(name__contains=key_word) |
        Q(author__username__contains=key_word) |
        Q(description__contains=key_word),
        is_published=True
    )
    context = {"videos_list": videos_query}
    return render(request, "videos.html", context)

def profile_create(request):
    context = {}
    if request.method == "POST":
        profile_form = ProfileForm(
            data=request.POST,
            files=request.FILES
        )
        if profile_form.is_valid():
            profile_object = profile_form.save(commit=False)
            profile_object.user = request.user
            profile_object.save()
            messages.success(request, "Профиль и канал успешно созданы")
            return redirect(f'/profile/{profile_object.id}/')
        else:
            messages.error(request, "Ошибка при создании профиля")

    profile_form = ProfileForm()
    context["profile_form"] = profile_form
    return render(
        request=request,
        template_name="profile_create.html",
        context=context
    )

def profile_detail(request, id):
    context = {}
    profile_object = Profile.objects.get(id=id)
    context["profile_object"] = profile_object

    # subscribers_qty = profile_object.subscribers.count()
    subscribers_qty = User.objects.filter(subscriptions=profile_object).count()
    context["subscribers_qty"] = subscribers_qty

    # [video_1, video_2, ...] видео этого пользователя
    videos_list = profile_object.user.video_set.all()
    # videos_list = Video.objects.filter(author=profile_object.user)
    context["videos_list"] = videos_list 


    return render(
        request,
        'profile.html',
        context
    )

def profile_update(request, id):
    context = {}
    profile_object = Profile.objects.get(id=id)
    if request.user == profile_object.user:
        if request.method == "POST":
            profile_form = ProfileForm(
                instance=profile_object,
                data=request.POST,
                files=request.FILES,
            )
            if profile_form.is_valid():
                profile_form.save()
                messages.success(request, "Профиль успешно обновлён!")
                return redirect(profile_detail, id=profile_object.id)

        profile_form = ProfileForm(instance=profile_object)
        context["profile_form"] = profile_form
        return render(request, "profile_update.html", context)
    else:
        return HttpResponse("Нет доступа")


class ProfileUpdate(View):
    # read
    def get(self, request, *args, **kwargs):
        context = {}
        profile_object = Profile.objects.get(id=kwargs.get("pk"))
        profile_form = ProfileForm(instance=profile_object)
        context["profile_form"] = profile_form
        return render(request, "profile_update.html", context)
    
    # update
    def post(self, request, *args, **kwargs):
        profile_object = Profile.objects.get(id=kwargs.get("pk"))
        if request.user == profile_object.user:
            profile_form = ProfileForm(
                instance=profile_object,
                data=request.POST,
                files=request.FILES,
            )
            if profile_form.is_valid():
                profile_form.save()
                messages.success(request, "Профиль успешно обновлён!")
                return redirect("profile-update-cbv", pk=profile_object.id)
            else:
                return HttpResponse("Данные не валидны", status=400)
        else:
            return HttpResponse("Нет доступа", status=403)




def profile_delete(request, id):
    context = {}
    if request.user == profile_object.user:
        profile_object = Profile.objects.get(id=id)
        context["profile_object"] = profile_object

        if request.method == "POST":
            profile_object.delete()
            return redirect("home")
        return render(request, "profile_delete.html", context)
    else:
        return HttpResponse("Нет доступа")


def subscriber_add(request,id):
    if request.method == "POST":
        profile_object = Profile.objects.get(id=id)
        profile_object.subscribers.add(request.user)
        profile_object.save()
        return redirect(profile_detail, id=profile_object.id)

def subscriber_remove(request,id):
    if request.method == "POST":
        profile_object = Profile.objects.get(id=id)
        profile_object.subscribers.remove(request.user)
        profile_object.save()
        return redirect(profile_detail, id=profile_object.id)

playlist/views.py
from django.shortcuts import render, redirect
from .models import UserPlayList
from .forms import PlayListForm
from django.contrib.auth.decorators import login_required  

@login_required
def playlists(request):
    query_result = UserPlayList.objects.filter(owner=request.user) 

    context = {"objects_list": query_result}
    return render(request, 'playlists.html', context)

@login_required
def playlist_info(request, id):
    playlist_object = UserPlayList.objects.get(id=id, owner=request.user)  
    context = {"playlist_object": playlist_object}
    return render(request, "playlist_info.html", context)

@login_required
def playlist_add(request):
    if request.method == "POST":
        name = request.POST["playlist_name"]
        description = request.POST["description"]
        playlist_object = UserPlayList.objects.create(
            name=name,
            description=description,
            owner=request.user,  # Устанавливаем текущего пользователя как владельца
        )
        return redirect(playlist_info, id=playlist_object.id)
    
    return render(request, "playlist_add.html")


def playlist_df_add(request):
    context = {}
    if request.method == "POST":
        # код создания playlist 

        # создаём объект формы с значениями
        playlist_form = PlayListForm(request.POST)
        # проверка валидности
        if playlist_form.is_valid():
            # создаём запись в БД
            playlist_object = playlist_form.save()
            return redirect(playlist_info, id=playlist_object.id)
    
    playlist_form = PlayListForm()
    context["playlist_form"] = playlist_form
    return render(request, "playlist_df_add.html", context)

video/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from django.views import View
from .models import *
from .forms import *


def videos(request):
    videos_list = Video.objects.all()
    context = {"videos_list": videos_list}
    return render(
        request,
        'videos.html',
        context
    )

def video(request, id):
    # 7
    # SELECT * FROM video_video WHERE id = 7;
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return HttpResponse('Вы не авторизованы', status=401)
    try:
        video_object = Video.objects.get(id=id)
    except:
        return HttpResponse("Не найдено", status=404)
    context = {}
    if request.user.is_authenticated:
        video_view, created = VideoView.objects.get_or_create(
            user=request.user,
            video=video_object,
        )
        if request.method == 'POST':
            if "txt" in request.POST:
                comment_form = CommentForm(request.POST)
                if comment_form.is_valid():
                    comment = comment_form.save(commit=False) # ещё нет записи в БД
                    comment.user = request.user
                    comment.video = video_object
                    comment.save() # сохраняем в БД
                    messages.success(request, 'Комментарий успешно добавлен.')
                else:
                    messages.error(request, 'Ошибка! Данные не валидны')
            elif "like" in request.POST:
                video_object.likes += 1
                video_object.save()
            elif "dislike" in request.POST:
                video_object.dislikes.add(request.user)
                messages.success(request, 'Вы поставили дизлайк.')  
            # return redirect(video, id=video_object.id)
    context = {
        "video": video_object,
        "comment_form": CommentForm()

    }
    return render(request, 'video.html', context)

def video_add(request):
    if request.method == "GET":
        return render(request, 'video_add.html')
    elif request.method == "POST":
        name = request.POST["video_name"]
        video_file = request.FILES["video_file"]
        video_object = Video(
            name=name,
            file_path=video_file,
            author=request.user
        )
        # video_object.description = "hello world"
        # INSERT INTO ...
        video_object.save()
        return redirect(video, id=video_object.id)

def video_update(request, id):
    video_object = Video.objects.get(id=id)
    context = {"video": video_object}

    if request.method == "POST":
        name = request.POST["video_name"]
        video_object.name = name
        video_object.save()
        return redirect(video, id=video_object.id)

    return render(request, 'video_update.html', context)

def video_delete(request, id):
    video_object = Video.objects.get(id=id)
    video_object.delete()
    return redirect(videos)


class VideoUpdate(View):
    # read
    def get(self, request, *args, **kwargs):
        context = {}
        video_object = Video.objects.get(id=kwargs.get("pk"))
        video_form = VideoForm(
            instance=video_object,
        )
        context["video_form"] = video_form
        return render(request, "video_update_cbv.html", context)

    # update
    def post(self, request, *args, **kwargs):
        video_object = Video.objects.get(id=kwargs.get("pk"))
        if request.user == video_object.author:
            video_form = VideoForm(
                instance=video_object,
                data=request.POST
            )
            if video_form.is_valid():
                video_form.save()
                messages.success(request, "Видео успешно обновлено!")
                return redirect("video-update-cbv", pk=video_object.id)
            else:
                return HttpResponse("Данные не валидны", status=400)
        else:
            return HttpResponse("Нет доступа", status=403)

core/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <div>
        Это страница аналог Youtube. Проект учебный
    </div>
{% endblock %}

core/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="shortcut icon" href="{% static 'logo.png' %}" type="image/x-icon">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <script src="{% static 'myscript.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <img src="{% static 'logo.png' %}" height="45px" alt="logo">
        </a>
        <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar" aria-expanded="false">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="mynavbar">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link"href="/">Домой</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/videos/">Список видео</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'short_list' %}">Shorts</a>
          </li>
            <li class="nav-item">
              <a class="nav-link" href="/about/">О нас</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/playlists/">Плейлисты</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Добавить</a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'playlist-add' %}">Добавить плейлист</a></li>
                  <li><a class="dropdown-item" href="{% url 'video-add' %}">Добавить видео</a></li>
                  <li><a class="dropdown-item" href="{% url 'playlist-df-add' %}">Добавить плейлист (df)</a></li>
                  <li><a class="dropdown-item" href="{% url 'profile-create' %}">Добавить профиль</a></li>
                </ul>
              </li>
              {% if request.user.profile %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'profile-detail' request.user.profile.id %}">Мой профиль</a>
                </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'sign-out' %}">Выйти</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'registration' %}">Регистрация</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'sign-in' %}">Вход</a>
              </li>
            {% endif %}
          </ul>
          <form class="d-flex mx-1" action="/search/">
            <input class="form-control me-2" type="text" name="key_word" placeholder="Введите">
            <button class="btn btn-dark">Поиск</button>
          </form>
          <div>
            {% if request.user.profile.photo %}
                <img src="{{ request.user.profile.photo.url }}" height="40px" alt="">
            {% else %}
                <img src="{% static 'logo_default.jpg' %}" height="40px" alt="">
            {% endif %}
            <br>
            <a
                {% if request.user.profile %}
                    href="{% url 'profile-detail' request.user.profile.id %}"
                {% endif %}
                class="text-white">
                {{ request.user.username }}
            </a>
        </div>
          </div>
        </div>
      </div>
    </nav>
    <br>
    {% bootstrap_messages %}
    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>

    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    
</body>
</html>

core/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div>
        Hello from templates
    </div>
{% endblock %}

core/templates/playlist_add.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <input type="text" name="playlist_name">
        <input type="text" name="description">
        <button>Добавить</button>
    </form>
{% endblock %}

core/templates/playlist_df_add.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form playlist_form %}
        <button class="btn btn-primary">Добавить</button>
    </form>
{% endblock %}

core/templates/playlist_info.html
{% extends 'base.html' %}

{% block content %}
  <h2>{{ playlist_object.name }}</h2>
  <p>Описание: {{ playlist_object.description }}</p>
  <p>Количество видео: {{ playlist_object.videos_qty }}</p>
  <p>Количество просмотров: {{ playlist_object.views_qty }}</p>
  <p>Опубликовано: {% if playlist_object.is_published %}Да{% else %}Нет{% endif %}</p>
  <p>Владелец: {{ playlist_object.owner.username }}</p>
{% endblock %}

core/templates/playlists.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h2>Ваши плейлисты</h2>
  <ul class="list-group">
    {% for playlist in objects_list %}
      <li class="list-group-item">
        <a href="{% url 'playlist-info' id=playlist.id %}">{{ playlist.name }}</a>
        (Владелец: {{ playlist.owner.username }})
      </li>
    {% endfor %}
  </ul>
{% endblock %}

core/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div>
        {% if profile_object.photo and profile_object.photo.url %}
            <img src="{{ profile_object.photo.url }}" alt="" height="250px">
        {% else %}
            <img src="{% static 'logo_default.jpg' %}" alt="" height="250px">
        {% endif %}
        <h3>Подписчиков: {{ subscribers_qty }}</h3>
        <h3>Название канала: {{ profile_object.channel_name }}</h3>
        <h3>Пользователь: {{ profile_object.user.username }}</h3>
    </div>
    {% if request.user == profile_object.user %}
        <a class="btn btn-warning" href="{% url 'profile-update' profile_object.id %}">Изменить</a>
        <a class="btn btn-danger" href="{% url 'profile-delete' profile_object.id %}">Удалить</a>
    {% else %}
        <div>
            {% if request.user in profile_object.subscribers.all %}
                <form action="{% url 'subscriber-remove' profile_object.id %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-danger">Отписаться</button>
                </form>
            {% else %}
                <form action="{% url 'subscriber-add' profile_object.id %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-info">Подписаться</button>
                </form>
            {% endif %}
        </div>
    {% endif %}
    <h3>Видео этого канала:</h3>
    <div class="row">
        {% for video in videos_list %}
            <div class="col-lg-4 col-md-6 col-sm-12">
                <a href="/video/{{ video.id }}/">
                    <video width="95%">
                        <source src="{{ video.file_path.url }}">
                    </video>
                    <h3>{{ video.name }}</h3>
                    <span><img height="20px" src="{% static 'like.svg' %}" alt=""> {{ video.likes }}</span> 
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

core/templates/profile_create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
    <h2>Создать профиль</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form profile_form %}
        <button class="btn btn-success">Создать</button>
    </form>
{% endblock %}

core/templates/profile_delete.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
    <h2>Удалить профиль пользователя {{ profile_object.user.username }}?</h2>
    <form method="POST">
        {% csrf_token %}
        <button class="btn btn-danger">Да</button>
        <a class="btn btn-warning" href="{% url 'profile-detail' profile_object.id %}">Нет</a>
    </form>

{% endblock %}

core/templates/profile_update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
    <h2>Обновить профиль</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form profile_form %}
        <button>Сохранить</button>
    </form>

{% endblock %}

core/templates/video.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
    <h1>{{ video.name }}</h1>
    {% if video.author %}
        <h2>Автор:
            <a href="
                {% if video.author.profile %}
                    {% url 'profile-detail' video.author.profile.id %}
                {% endif %}
            ">
                {{ video.author.username }}
            </a>
        </h2>
    {% endif %}
    <h3>Лайков: {{ video.likes }}</h2>
    <h3>Просмотры: {{ video.videoview_set.count }}</h2>
    <h3>Просмотрено пользователями:</h3>
    {% for view in video.videoview_set.all %}
        <div> 
            {{ view.user.username }}
        </div>
    {% endfor %}
    <hr>
    <p>
        <video width="500" controls src="{{ video.file_path.url }}">
        </video>
    </p>
    <!-- Только для автора -->
    {% if request.user == video.author %}
        <a href="{% url 'video-update-cbv' video.id %}" class="btn btn-warning">Изменить</a>
        <a href="{% url 'video-delete' video.id %}" class="btn btn-danger">Удалить</a>
    {% endif %}

    <!-- Только для авторизованного -->
    {% if request.user.is_authenticated %}
        <div class="likes-block">
            <form method="POST">
                {% csrf_token %}
                <button name="like">
                    <span>
                        <img height="20px" src="{% static 'like.svg' %}" alt="">
                        {{ video.likes }}
                    </span>
                </button>
            </form>
            <form method="POST">
                {% csrf_token %}
                <button name="dislike">
                    <span>
                        <img height="20px" src="{% static 'dislike.svg' %}" alt="">
                        {{ video.dislikes.count }}
                    </span>
                </button>
            </form>
        </div>
    {% endif %}

    <hr>
    <h2>Комментарии</h2>
    <p>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form comment_form %}
            {% if comment_form.errors %}
                <div class="alert alert-danger">
                    {{ comment_form.errors }}
                </div>
            {% endif %}
            <button type="submit" class="btn btn-primary">Добавить комментарий</button>
        </form>
    </p>
    {% for comment in video.comment_set.all %}
        <div class="card mb-3">
            <div class="card-header">
                <span class="font-weight-bold">{{ comment.user.username }}</span>
                <span class="text-muted">{{ comment.created_by|date:"F d, Y H:i" }}</span>
            </div>
            <div class="card-body">
                <p class="card-text">{{ comment.txt }}</p>
            </div>
        </div>
    {% endfor %}
{% endblock %}

core/templates/video_add.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>
            <input class="form-control" type="text" name="video_name" required maxlength="60">
        </p>
        <p>
            <input class="form-control" type="file" name="video_file" required>
        </p>
        <button class="btn btn-primary">Загрузить</button>
    </form>
{% endblock %}

core/templates/video_update.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <p>
            <input class="form-control" type="text" value="{{ video.name }}" name="video_name">
        </p>
        <button class="btn btn-primary">Обновить</button>
    </form>
{% endblock %}